# Generated by Django 4.2.23 on 2025-06-12 05:30

import app_bookmark.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('title', models.CharField(max_length=500)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=app_bookmark.models.bookmark_thumbnail_path)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportedSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('scraper_class', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('ERROR', 'Error')], max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('scraping_duration', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bookmark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_bookmark.bookmark')),
            ],
        ),
        migrations.AddField(
            model_name='bookmark',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_bookmark.supportedsite'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user_id', 'url')},
        ),
    ]
