# Generated by Django 4.2.23 on 2025-06-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookmark', '0002_supportedsite_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='user_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
