# Generated by Django 4.2.23 on 2025-06-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookmark', '0003_alter_bookmark_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='url',
            field=models.URLField(max_length=767),
        ),
    ]
