# Generated by Django 4.2.23 on 2025-06-14 02:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookmark', '0004_alter_bookmark_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='url',
            field=models.URLField(validators=[django.core.validators.URLValidator()]),
        ),
    ]
