# Generated by Django 4.2.23 on 2025-06-14 02:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookmark', '0006_alter_bookmark_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapinglog',
            name='url',
            field=models.URLField(max_length=767, validators=[django.core.validators.URLValidator()]),
        ),
    ]
